package com.bingoapp.db;

// Generated 12 Sep, 2013 6:34:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblEventcommentsDetails generated by hbm2java
 */
public class TblEventcommentsDetails implements java.io.Serializable {

	private Integer commentPk;
	private TblUserrootMaster tblUserrootMaster;
	private TblUserMaster tblUserMaster;
	private String commentSocialtype;
	private byte[] commentText;
	private String commentLink;
	private byte[] commentPhoto;
	private String userId;
	private String eventId;
	private String commentId;
	private Date commentCreatedTime;
	private Double commentLatitude;
	private Double commentLongitude;

	public TblEventcommentsDetails() {
	}

	public TblEventcommentsDetails(TblUserrootMaster tblUserrootMaster,
			TblUserMaster tblUserMaster, String commentSocialtype,
			byte[] commentText, String commentLink, byte[] commentPhoto,
			String userId, String eventId, String commentId,
			Date commentCreatedTime, Double commentLatitude,
			Double commentLongitude) {
		this.tblUserrootMaster = tblUserrootMaster;
		this.tblUserMaster = tblUserMaster;
		this.commentSocialtype = commentSocialtype;
		this.commentText = commentText;
		this.commentLink = commentLink;
		this.commentPhoto = commentPhoto;
		this.userId = userId;
		this.eventId = eventId;
		this.commentId = commentId;
		this.commentCreatedTime = commentCreatedTime;
		this.commentLatitude = commentLatitude;
		this.commentLongitude = commentLongitude;
	}

	public Integer getCommentPk() {
		return this.commentPk;
	}

	public void setCommentPk(Integer commentPk) {
		this.commentPk = commentPk;
	}

	public TblUserrootMaster getTblUserrootMaster() {
		return this.tblUserrootMaster;
	}

	public void setTblUserrootMaster(TblUserrootMaster tblUserrootMaster) {
		this.tblUserrootMaster = tblUserrootMaster;
	}

	public TblUserMaster getTblUserMaster() {
		return this.tblUserMaster;
	}

	public void setTblUserMaster(TblUserMaster tblUserMaster) {
		this.tblUserMaster = tblUserMaster;
	}

	public String getCommentSocialtype() {
		return this.commentSocialtype;
	}

	public void setCommentSocialtype(String commentSocialtype) {
		this.commentSocialtype = commentSocialtype;
	}

	public byte[] getCommentText() {
		return this.commentText;
	}

	public void setCommentText(byte[] commentText) {
		this.commentText = commentText;
	}

	public String getCommentLink() {
		return this.commentLink;
	}

	public void setCommentLink(String commentLink) {
		this.commentLink = commentLink;
	}

	public byte[] getCommentPhoto() {
		return this.commentPhoto;
	}

	public void setCommentPhoto(byte[] commentPhoto) {
		this.commentPhoto = commentPhoto;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getEventId() {
		return this.eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	public String getCommentId() {
		return this.commentId;
	}

	public void setCommentId(String commentId) {
		this.commentId = commentId;
	}

	public Date getCommentCreatedTime() {
		return this.commentCreatedTime;
	}

	public void setCommentCreatedTime(Date commentCreatedTime) {
		this.commentCreatedTime = commentCreatedTime;
	}

	public Double getCommentLatitude() {
		return this.commentLatitude;
	}

	public void setCommentLatitude(Double commentLatitude) {
		this.commentLatitude = commentLatitude;
	}

	public Double getCommentLongitude() {
		return this.commentLongitude;
	}

	public void setCommentLongitude(Double commentLongitude) {
		this.commentLongitude = commentLongitude;
	}

}
