package com.bingoapp.db;

// Generated 12 Sep, 2013 6:34:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Tbleventdetails generated by hbm2java
 */
public class Tbleventdetails implements java.io.Serializable {

	private int eventId;
	private TblUserrootMaster tblUserrootMaster;
	private byte[] eventName;
	private byte[] eventImg;
	private byte[] eventDesc;
	private String eventPlace;
	private String eventPlaceLatilongi;
	private Date eventDate;
	private Integer adminPk;
	private String eventFbId;
	private String eventType;
	private Date eventStartDate;
	private Date eventEndDate;
	private String eventImgType;
	private Double eventLatitude;
	private Double eventLongitude;

	public Tbleventdetails() {
	}

	public Tbleventdetails(int eventId) {
		this.eventId = eventId;
	}

	public Tbleventdetails(int eventId, TblUserrootMaster tblUserrootMaster,
			byte[] eventName, byte[] eventImg, byte[] eventDesc,
			String eventPlace, String eventPlaceLatilongi, Date eventDate,
			Integer adminPk, String eventFbId, String eventType,
			Date eventStartDate, Date eventEndDate, String eventImgType,
			Double eventLatitude, Double eventLongitude) {
		this.eventId = eventId;
		this.tblUserrootMaster = tblUserrootMaster;
		this.eventName = eventName;
		this.eventImg = eventImg;
		this.eventDesc = eventDesc;
		this.eventPlace = eventPlace;
		this.eventPlaceLatilongi = eventPlaceLatilongi;
		this.eventDate = eventDate;
		this.adminPk = adminPk;
		this.eventFbId = eventFbId;
		this.eventType = eventType;
		this.eventStartDate = eventStartDate;
		this.eventEndDate = eventEndDate;
		this.eventImgType = eventImgType;
		this.eventLatitude = eventLatitude;
		this.eventLongitude = eventLongitude;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public TblUserrootMaster getTblUserrootMaster() {
		return this.tblUserrootMaster;
	}

	public void setTblUserrootMaster(TblUserrootMaster tblUserrootMaster) {
		this.tblUserrootMaster = tblUserrootMaster;
	}

	public byte[] getEventName() {
		return this.eventName;
	}

	public void setEventName(byte[] eventName) {
		this.eventName = eventName;
	}

	public byte[] getEventImg() {
		return this.eventImg;
	}

	public void setEventImg(byte[] eventImg) {
		this.eventImg = eventImg;
	}

	public byte[] getEventDesc() {
		return this.eventDesc;
	}

	public void setEventDesc(byte[] eventDesc) {
		this.eventDesc = eventDesc;
	}

	public String getEventPlace() {
		return this.eventPlace;
	}

	public void setEventPlace(String eventPlace) {
		this.eventPlace = eventPlace;
	}

	public String getEventPlaceLatilongi() {
		return this.eventPlaceLatilongi;
	}

	public void setEventPlaceLatilongi(String eventPlaceLatilongi) {
		this.eventPlaceLatilongi = eventPlaceLatilongi;
	}

	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	public Integer getAdminPk() {
		return this.adminPk;
	}

	public void setAdminPk(Integer adminPk) {
		this.adminPk = adminPk;
	}

	public String getEventFbId() {
		return this.eventFbId;
	}

	public void setEventFbId(String eventFbId) {
		this.eventFbId = eventFbId;
	}

	public String getEventType() {
		return this.eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	public Date getEventStartDate() {
		return this.eventStartDate;
	}

	public void setEventStartDate(Date eventStartDate) {
		this.eventStartDate = eventStartDate;
	}

	public Date getEventEndDate() {
		return this.eventEndDate;
	}

	public void setEventEndDate(Date eventEndDate) {
		this.eventEndDate = eventEndDate;
	}

	public String getEventImgType() {
		return this.eventImgType;
	}

	public void setEventImgType(String eventImgType) {
		this.eventImgType = eventImgType;
	}

	public Double getEventLatitude() {
		return this.eventLatitude;
	}

	public void setEventLatitude(Double eventLatitude) {
		this.eventLatitude = eventLatitude;
	}

	public Double getEventLongitude() {
		return this.eventLongitude;
	}

	public void setEventLongitude(Double eventLongitude) {
		this.eventLongitude = eventLongitude;
	}

}
