package com.bingoapp.db;

// Generated 12 Sep, 2013 6:34:44 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tblsequence generated by hbm2java
 */
public class Tblsequence implements java.io.Serializable {

	private Integer idpk;
	private String tablename;
	private Integer nextsequenceno;

	public Tblsequence() {
	}

	public Tblsequence(String tablename, Integer nextsequenceno) {
		this.tablename = tablename;
		this.nextsequenceno = nextsequenceno;
	}

	public Integer getIdpk() {
		return this.idpk;
	}

	public void setIdpk(Integer idpk) {
		this.idpk = idpk;
	}

	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public Integer getNextsequenceno() {
		return this.nextsequenceno;
	}

	public void setNextsequenceno(Integer nextsequenceno) {
		this.nextsequenceno = nextsequenceno;
	}

}
