package com.bingoapp.db;

// Generated 12 Sep, 2013 6:34:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblUserrootMaster generated by hbm2java
 */
public class TblUserrootMaster implements java.io.Serializable {

	private int userrootId;
	private String userrootName;
	private Set<TblUserrootDetails> tblUserrootDetailses = new HashSet<TblUserrootDetails>(
			0);
	private Set<TblEventcommentsDetails> tblEventcommentsDetailses = new HashSet<TblEventcommentsDetails>(
			0);
	private Set<TblUserMaster> tblUserMasters = new HashSet<TblUserMaster>(0);
	private Set<Tbleventdetails> tbleventdetailses = new HashSet<Tbleventdetails>(
			0);

	public TblUserrootMaster() {
	}

	public TblUserrootMaster(int userrootId) {
		this.userrootId = userrootId;
	}

	public TblUserrootMaster(int userrootId, String userrootName,
			Set<TblUserrootDetails> tblUserrootDetailses,
			Set<TblEventcommentsDetails> tblEventcommentsDetailses,
			Set<TblUserMaster> tblUserMasters,
			Set<Tbleventdetails> tbleventdetailses) {
		this.userrootId = userrootId;
		this.userrootName = userrootName;
		this.tblUserrootDetailses = tblUserrootDetailses;
		this.tblEventcommentsDetailses = tblEventcommentsDetailses;
		this.tblUserMasters = tblUserMasters;
		this.tbleventdetailses = tbleventdetailses;
	}

	public int getUserrootId() {
		return this.userrootId;
	}

	public void setUserrootId(int userrootId) {
		this.userrootId = userrootId;
	}

	public String getUserrootName() {
		return this.userrootName;
	}

	public void setUserrootName(String userrootName) {
		this.userrootName = userrootName;
	}

	public Set<TblUserrootDetails> getTblUserrootDetailses() {
		return this.tblUserrootDetailses;
	}

	public void setTblUserrootDetailses(
			Set<TblUserrootDetails> tblUserrootDetailses) {
		this.tblUserrootDetailses = tblUserrootDetailses;
	}

	public Set<TblEventcommentsDetails> getTblEventcommentsDetailses() {
		return this.tblEventcommentsDetailses;
	}

	public void setTblEventcommentsDetailses(
			Set<TblEventcommentsDetails> tblEventcommentsDetailses) {
		this.tblEventcommentsDetailses = tblEventcommentsDetailses;
	}

	public Set<TblUserMaster> getTblUserMasters() {
		return this.tblUserMasters;
	}

	public void setTblUserMasters(Set<TblUserMaster> tblUserMasters) {
		this.tblUserMasters = tblUserMasters;
	}

	public Set<Tbleventdetails> getTbleventdetailses() {
		return this.tbleventdetailses;
	}

	public void setTbleventdetailses(Set<Tbleventdetails> tbleventdetailses) {
		this.tbleventdetailses = tbleventdetailses;
	}

}
