package com.bingoapp.db;

// Generated 12 Sep, 2013 6:34:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblUserMaster generated by hbm2java
 */
public class TblUserMaster implements java.io.Serializable {

	private Integer userPk;
	private TblUserrootMaster tblUserrootMaster;
	private String userName;
	private String userUsername;
	private String userLocation;
	private String userLatilongi;
	private String userEmailid;
	private String userPhoneno;
	private String userAddress;
	private String userPincode;
	private byte[] userPhoto;
	private String userSocialtype;
	private String userId;
	private Double userLatitude;
	private Double userLongitude;
	private String userImageContentType;
	private Set<TblEventcommentsDetails> tblEventcommentsDetailses = new HashSet<TblEventcommentsDetails>(
			0);

	public TblUserMaster() {
	}

	public TblUserMaster(TblUserrootMaster tblUserrootMaster, String userName,
			String userUsername, String userLocation, String userLatilongi,
			String userEmailid, String userPhoneno, String userAddress,
			String userPincode, byte[] userPhoto, String userSocialtype,
			String userId, Double userLatitude, Double userLongitude,
			String userImageContentType,
			Set<TblEventcommentsDetails> tblEventcommentsDetailses) {
		this.tblUserrootMaster = tblUserrootMaster;
		this.userName = userName;
		this.userUsername = userUsername;
		this.userLocation = userLocation;
		this.userLatilongi = userLatilongi;
		this.userEmailid = userEmailid;
		this.userPhoneno = userPhoneno;
		this.userAddress = userAddress;
		this.userPincode = userPincode;
		this.userPhoto = userPhoto;
		this.userSocialtype = userSocialtype;
		this.userId = userId;
		this.userLatitude = userLatitude;
		this.userLongitude = userLongitude;
		this.userImageContentType = userImageContentType;
		this.tblEventcommentsDetailses = tblEventcommentsDetailses;
	}

	public Integer getUserPk() {
		return this.userPk;
	}

	public void setUserPk(Integer userPk) {
		this.userPk = userPk;
	}

	public TblUserrootMaster getTblUserrootMaster() {
		return this.tblUserrootMaster;
	}

	public void setTblUserrootMaster(TblUserrootMaster tblUserrootMaster) {
		this.tblUserrootMaster = tblUserrootMaster;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserUsername() {
		return this.userUsername;
	}

	public void setUserUsername(String userUsername) {
		this.userUsername = userUsername;
	}

	public String getUserLocation() {
		return this.userLocation;
	}

	public void setUserLocation(String userLocation) {
		this.userLocation = userLocation;
	}

	public String getUserLatilongi() {
		return this.userLatilongi;
	}

	public void setUserLatilongi(String userLatilongi) {
		this.userLatilongi = userLatilongi;
	}

	public String getUserEmailid() {
		return this.userEmailid;
	}

	public void setUserEmailid(String userEmailid) {
		this.userEmailid = userEmailid;
	}

	public String getUserPhoneno() {
		return this.userPhoneno;
	}

	public void setUserPhoneno(String userPhoneno) {
		this.userPhoneno = userPhoneno;
	}

	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getUserPincode() {
		return this.userPincode;
	}

	public void setUserPincode(String userPincode) {
		this.userPincode = userPincode;
	}

	public byte[] getUserPhoto() {
		return this.userPhoto;
	}

	public void setUserPhoto(byte[] userPhoto) {
		this.userPhoto = userPhoto;
	}

	public String getUserSocialtype() {
		return this.userSocialtype;
	}

	public void setUserSocialtype(String userSocialtype) {
		this.userSocialtype = userSocialtype;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Double getUserLatitude() {
		return this.userLatitude;
	}

	public void setUserLatitude(Double userLatitude) {
		this.userLatitude = userLatitude;
	}

	public Double getUserLongitude() {
		return this.userLongitude;
	}

	public void setUserLongitude(Double userLongitude) {
		this.userLongitude = userLongitude;
	}

	public String getUserImageContentType() {
		return this.userImageContentType;
	}

	public void setUserImageContentType(String userImageContentType) {
		this.userImageContentType = userImageContentType;
	}

	public Set<TblEventcommentsDetails> getTblEventcommentsDetailses() {
		return this.tblEventcommentsDetailses;
	}

	public void setTblEventcommentsDetailses(
			Set<TblEventcommentsDetails> tblEventcommentsDetailses) {
		this.tblEventcommentsDetailses = tblEventcommentsDetailses;
	}

}
