package com.bingoapp.db;

// Generated 12 Sep, 2013 6:34:44 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblUserrootDetails generated by hbm2java
 */
public class TblUserrootDetails implements java.io.Serializable {

	private int userrootdetailsId;
	private TblUserrootMaster tblUserrootMaster;
	private TblUserownMaster tblUserownMaster;

	public TblUserrootDetails() {
	}

	public TblUserrootDetails(int userrootdetailsId) {
		this.userrootdetailsId = userrootdetailsId;
	}

	public TblUserrootDetails(int userrootdetailsId,
			TblUserrootMaster tblUserrootMaster,
			TblUserownMaster tblUserownMaster) {
		this.userrootdetailsId = userrootdetailsId;
		this.tblUserrootMaster = tblUserrootMaster;
		this.tblUserownMaster = tblUserownMaster;
	}

	public int getUserrootdetailsId() {
		return this.userrootdetailsId;
	}

	public void setUserrootdetailsId(int userrootdetailsId) {
		this.userrootdetailsId = userrootdetailsId;
	}

	public TblUserrootMaster getTblUserrootMaster() {
		return this.tblUserrootMaster;
	}

	public void setTblUserrootMaster(TblUserrootMaster tblUserrootMaster) {
		this.tblUserrootMaster = tblUserrootMaster;
	}

	public TblUserownMaster getTblUserownMaster() {
		return this.tblUserownMaster;
	}

	public void setTblUserownMaster(TblUserownMaster tblUserownMaster) {
		this.tblUserownMaster = tblUserownMaster;
	}

}
